#!/bin/bash
#
# Copyright (C) 2022~2023 UsiFX <xprjkts@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License
#
# This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#

### Local Variables

# \e colors
BLUE='\e[1;34m'
GREEN='\e[1;32m'
PURPLE='\e[1;35m'
CYAN='\e[1;36m'
RED='\e[1;31m'
WHITE='\e[1;37m'
YELLOW='\e[01;33m'

NITRON_LOG_DIR='/cache'
PROMPT_COMMAND='sync'

### Debugging
set -x


### Funcs
printn()
{
  while getopts ":n:e:w:i:" printn_opts; do
    case "${printn_opts}" in
      n) printf "[*] $2" ;;
      e) printf "[×] $2"; return 1 ;;
      w) printf "[!] $2" ;;
      i) printf "[i] $2" ;;
    esac
  done
}
