#!/bin/bash
# shellcheck disable=SC2034
# shellcheck disable=SC2059
# shellcheck disable=SC1091
# shellcheck disable=SC2015
# shellcheck disable=SC1087
# shellcheck disable=SC2181
#
# Copyright (C) 2022~2023 UsiFX <xprjkts@gmail.com>
# Kartik728 <titanupdates728@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License
#
# This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#

### Local Variables

# \e colors
BLUE='\e[1;34m'
GREEN='\e[1;32m'
PURPLE='\e[1;35m'
CYAN='\e[1;36m'
RED='\e[1;31m'
WHITE='\e[1;37m'
YELLOW='\e[01;33m'
STOCK='\e[1;0m'

export NITRON_FORCECHECK_UPDATE
export NITRON_VERSION='1.0.5-staging'
grep -q "androidboot" /proc/cmdline && HEADER_SOURCE="/system/etc" || HEADER_SOURCE="${PREFIX/\/usr}/usr/include"
grep -q "androidboot" /proc/cmdline && NITRON_LOG_DIR='/cache' || NITRON_LOG_DIR='/tmp'
PR_PREFIX="nitron_broadcast"
DAEMON_SOURCE=$(dirname "$0")
PROMPT_COMMAND='sync'

# Include headers
if [[ ! -f $HEADER_SOURCE/nitron_headers.sh ]]; then
	echo "missing header, $HEADER_SOURCE/nitron_headers.sh"
	exit 1
else
	source "$HEADER_SOURCE"/nitron_headers.sh
fi

printn() {
	[[ "$1" == "-n" ]] && printf "[${BLUE}*${STOCK}] $2\n"

	[[ "$1" == "-e" ]] && {
		printf "[${RED}×${STOCK}] $2\n"
		exit 1
	}

	[[ "$1" == "-w" ]] && printf "[${YELLOW}!${STOCK}] $2\n"

	[[ "$1" == "-i" ]] && printf "[${CYAN}i${STOCK}] $2 \n"

	[[ "$1" == "-l" ]] && echo "[$(date +%I:%M:%S)] nitrond: $PR_PREFIX[0]: $2" >>"$NITRON_LOG_DIR"/nitron.log

	[[ "$1" == "-lf" ]] && echo "[$(date +%I:%M:%S)] nitrond: $PR_PREFIX[1]: $2" >>"$NITRON_LOG_DIR"/nitron.log
}

writen() {
	[[ ! -f "$1" ]] && {
		echo "[$(date +%I:%M:%S)] nitrond: $1: not found, skipping..." >> "$NITRON_LOG_DIR"/nitron.log
		return 1
	}

	# Make file writable
	chmod +w "$1" 2>/dev/null

	# Write new value, bail out if it fail
	if ! echo "$2" > "$1" >/dev/null; then
		echo "[$(date +%I:%M:%S)] nitrond: $1: failed to change node" >> "$NITRON_LOG_DIR"/nitron.log
	else
		echo "[$(date +%I:%M:%S)] nitrond: $1: changed node[$2]" >> "$NITRON_LOG_DIR"/nitron.log
	fi
}

__magicn_help() {
	echo "
Usage: magicn [-g|-r|-y|-h]

Options:
 -g, --green   ~ switch to Battery mode
 -y, --yellow  ~ switch to Balanced mode
 -r, --red     ~ switch to Gaming mode
 -h, --help    ~ prints this menu
"
}

# Initialise OS Compatibility check
oschk

# Initialise Mode set
modelockn

# Initialise Android Magisk Module status set-er
apin -as

magicn() {
	PR_PREFIX="magicn"
	set_battery_mode() {
		setmoden "Battery"
		writen /proc/sys/kernel/perf_cpu_time_max_percent 2
		writen /proc/sys/kernel/sched_autogroup_enabled 1
		writen /proc/sys/kernel/sched_child_runs_first 0
		writen /proc/sys/kernel/sched_tunable_scaling 0
		writen /proc/sys/kernel/sched_migration_cost_ns 5000000
		writen /proc/sys/kernel/sched_nr_migrate 256
		writen /proc/sys/kernel/sched_schedstats 0
		writen /proc/sys/kernel/printk_devkmsg off
		writen /proc/sys/vm/dirty_background_ratio 2
		writen /proc/sys/vm/dirty_ratio 5
		writen /proc/sys/vm/dirty_expire_centisecs 500
		writen /proc/sys/vm/dirty_writeback_centisecs 500
		writen /proc/sys/vm/page-cluster 0
		writen /proc/sys/vm/stat_interval 10
		writen /proc/sys/vm/swappiness 100
		writen /proc/sys/vm/vfs_cache_pressure 100
		writen /proc/sys/net/ipv4/tcp_ecn 1
		writen /proc/sys/net/ipv4/tcp_fastopen 3
		writen /proc/sys/net/ipv4/tcp_syncookies 0
		writen /sys/module/ged/parameters/gx_game_mode 0
		writen /sys/module/ged/parameters/gx_force_cpu_boost 0
		writen /sys/module/ged/parameters/boost_amp 0
		writen /sys/module/ged/parameters/boost_extra 0
		writen /sys/module/ged/parameters/boost_gpu_enable 0
		writen /sys/module/ged/parameters/enable_cpu_boost 0
		writen /sys/module/ged/parameters/enable_gpu_boost 0
		writen /sys/module/ged/parameters/enable_game_self_frc_detect 0
		writen /sys/module/ged/parameters/gpu_idle 100
		writen /sys/block/mmcblk0/queue/scheduler noop
		writen /sys/block/mmcblk1/queue/scheduler noop
		writen /sys/block/sda/queue/scheduler noop
		writen /sys/block/sdb/queue/scheduler noop
		writen /proc/cpufreq/cpufreq_power_mode 1
		writen /proc/cpufreq/cpufreq_cci_mode 0
		writen /sys/devices/system/cpu/eas/enable 1
		writen /sys/devices/system/cpu/perf/enable 0
		writen /proc/gpufreq/gpufreq_opp_freq 99000
		writen /proc/ppm/enabled 0
		writen /proc/ppm/policy_status 1
		writen /sys/devices/system/cpu/cpufreq/policy0/scaling_governor powersave
		writen /sys/devices/system/cpu/cpufreq/policy4/scaling_governor schedutil
		writen /sys/devices/system/cpu/cpufreq/policy6/scaling_governor schedutil
		writen /proc/ppm/policy/hard_userlimit_max_cpu_freq 998000
		writen /proc/ppm/policy/hard_userlimit_min_cpu_freq 850000
		writen /dev/cpuset/foreground/cpus 0-5
		writen /dev/cpuset/background/cpus 0-7
		writen /dev/cpuset/system-background/cpus 0-7
		writen /dev/cpuset/top-app/cpus 0-7
		writen /dev/cpuset/restricted/cpus
		writen /dev/stune/background/schedtune.util.max.effective 0
		writen /dev/stune/background/schedtune.util.min.effective 0
		writen /dev/stune/background/schedtune.util.max 0
		writen /dev/stune/background/schedtune.util.min 0
		writen /dev/stune/background/schedtune.boost 0
		writen /dev/stune/background/schedtune.prefer_idle 1
		writen /dev/stune/foreground/schedtune.util.max.effective 1
		writen /dev/stune/foreground/schedtune.util.min.effective 0
		writen /dev/stune/foreground/schedtune.util.max 1
		writen /dev/stune/foreground/schedtune.util.min 0
		writen /dev/stune/foreground/schedtune.boost 0
		writen /dev/stune/foreground/schedtune.prefer_idle 1
		writen /dev/stune/top-app/schedtune.util.max.effective 0
		writen /dev/stune/top-app/schedtune.util.min.effective 0
		writen /dev/stune/top-app/schedtune.util.max 128
		writen /dev/stune/top-app/schedtune.util.min 0
		writen /dev/stune/top-app/schedtune.boost 0
		writen /dev/stune/top-app/schedtune.prefer_idle 1
		writen /dev/stune/schedtune.util.min 0
		writen /dev/stune/schedtune.util.max 512
		writen /dev/stune/schedtune.util.max.effective 512
		writen /dev/stune/schedtune.util.min.effective 0
		writen /dev/stune/schedtune.boost 0
		writen /dev/stune/schedtune.prefer_idle 1
	}
	set_balanced_mode() {
		setmoden "Balanced"
		writen /proc/sys/kernel/perf_cpu_time_max_percent 5
		writen /proc/sys/kernel/sched_autogroup_enabled 1
		writen /proc/sys/kernel/sched_child_runs_first 1
		writen /proc/sys/kernel/sched_tunable_scaling 0
		writen /proc/sys/kernel/sched_migration_cost_ns 5000000
		writen /proc/sys/kernel/sched_nr_migrate 32
		writen /proc/sys/kernel/sched_schedstats 0
		writen /proc/sys/kernel/printk_devkmsg off
		writen /proc/sys/vm/dirty_background_ratio 10
		writen /proc/sys/vm/dirty_ratio 30
		writen /proc/sys/vm/dirty_expire_centisecs 3000
		writen /proc/sys/vm/dirty_writeback_centisecs 3000
		writen /proc/sys/vm/page-cluster 0
		writen /proc/sys/vm/stat_interval 10
		writen /proc/sys/vm/swappiness 100
		writen /proc/sys/vm/vfs_cache_pressure 100
		writen /proc/sys/net/ipv4/tcp_ecn 1
		writen /proc/sys/net/ipv4/tcp_fastopen 3
		writen /proc/sys/net/ipv4/tcp_syncookies 0
		writen /sys/module/ged/parameters/gx_game_mode 0
		writen /sys/module/ged/parameters/gx_force_cpu_boost 0
		writen /sys/module/ged/parameters/boost_amp 0
		writen /sys/module/ged/parameters/boost_extra 0
		writen /sys/module/ged/parameters/boost_gpu_enable 0
		writen /sys/module/ged/parameters/enable_cpu_boost 0
		writen /sys/module/ged/parameters/enable_gpu_boost 0
		writen /sys/module/ged/parameters/enable_game_self_frc_detect 0
		writen /sys/module/ged/parameters/gpu_idle 100
		writen /proc/cpufreq/cpufreq_power_mode 0
		writen /proc/cpufreq/cpufreq_cci_mode 0
		writen /sys/devices/system/cpu/eas/enable 2
		writen /sys/devices/system/cpu/perf/enable 0
		writen /proc/gpufreq/gpufreq_opp_freq 0
		writen /sys/block/mmcblk0/queue/scheduler cfq
		writen /sys/block/mmcblk1/queue/scheduler cfq
		writen /sys/block/sda/queue/scheduler cfq
		writen /sys/block/sdb/queue/scheduler cfq
		writen /sys/devices/system/cpu/cpufreq/policy0/scaling_governor schedutil
		writen /sys/devices/system/cpu/cpufreq/policy4/scaling_governor schedutil
		writen /sys/devices/system/cpu/cpufreq/policy6/scaling_governor schedutil
		writen /proc/ppm/policy/hard_userlimit_max_cpu_freq 2000000
		writen /proc/ppm/policy/hard_userlimit_min_cpu_freq 850000
		writen /proc/ppm/policy/hard_userlimit_max_cpu_freq 1700000
		writen /proc/ppm/policy/hard_userlimit_min_cpu_freq 500000
		writen /dev/cpuset/foreground/cpus 0-7
		writen /dev/cpuset/background/cpus 0-6
		writen /dev/cpuset/system-background/cpus 0-4
		writen /dev/cpuset/top-app/cpus 0-7
		writen /dev/cpuset/restricted/cpus 0
		writen /dev/stune/background/schedtune.util.max.effective 0
		writen /dev/stune/background/schedtune.util.min.effective 0
		writen /dev/stune/background/schedtune.util.max 0
		writen /dev/stune/background/schedtune.util.min 0
		writen /dev/stune/background/schedtune.boost 0
		writen /dev/stune/foreground/schedtune.util.max.effective 1024
		writen /dev/stune/foreground/schedtune.util.min.effective 1024
		writen /dev/stune/foreground/schedtune.util.max 1024
		writen /dev/stune/foreground/schedtune.util.min 0
		writen /dev/stune/foreground/schedtune.boost 0
		writen /dev/stune/top-app/schedtune.util.max.effective 1024
		writen /dev/stune/top-app/schedtune.util.min.effective 0
		writen /dev/stune/top-app/schedtune.util.max 1024
		writen /dev/stune/top-app/schedtune.util.min 0
		writen /dev/stune/top-app/schedtune.boost 0
		writen /dev/stune/schedtune.util.min 0
		writen /dev/stune/schedtune.util.max 0
		writen /dev/stune/schedtune.util.max.effective 1024
		writen /dev/stune/schedtune.util.min.effective 0
		writen /dev/stune/schedtune.boost 0
	}
	set_gaming_mode() {
		setmoden "Gaming"
		writen /proc/sys/kernel/perf_cpu_time_max_percent 20
		writen /proc/sys/kernel/sched_autogroup_enabled 0
		writen /proc/sys/kernel/sched_child_runs_first 0
		writen /proc/sys/kernel/sched_tunable_scaling 0
		writen /proc/sys/kernel/sched_migration_cost_ns 5000000
		writen /proc/sys/kernel/sched_nr_migrate 128
		writen /proc/sys/kernel/sched_schedstats 0
		writen /proc/sys/kernel/printk_devkmsg off
		writen /proc/sys/vm/dirty_background_ratio 15
		writen /proc/sys/vm/dirty_ratio 30
		writen /proc/sys/vm/dirty_expire_centisecs 3000
		writen /proc/sys/vm/dirty_writeback_centisecs 3000
		writen /proc/sys/vm/page-cluster 0
		writen /proc/sys/vm/stat_interval 10
		writen /proc/sys/vm/swappiness 100
		writen /proc/sys/vm/vfs_cache_pressure 80
		writen /proc/sys/net/ipv4/tcp_ecn 1
		writen /proc/sys/net/ipv4/tcp_fastopen 3
		writen /proc/sys/net/ipv4/tcp_syncookies 0
		writen /sys/module/ged/parameters/gx_game_mode 1
		writen /sys/module/ged/parameters/gx_force_cpu_boost 1
		writen /sys/module/ged/parameters/boost_amp 1
		writen /sys/module/ged/parameters/boost_extra 1
		writen /sys/module/ged/parameters/boost_gpu_enable 1
		writen /sys/module/ged/parameters/enable_cpu_boost 1
		writen /sys/module/ged/parameters/enable_gpu_boost 1
		writen /sys/module/ged/parameters/enable_game_self_frc_detect 1
		writen /sys/module/ged/parameters/gpu_idle 0
		writen /proc/cpufreq/cpufreq_power_mode 3
		writen /proc/cpufreq/cpufreq_cci_mode 1
		writen /sys/devices/system/cpu/eas/enable 0
		writen /sys/devices/system/cpu/perf/enable 1
		writen /proc/ppm/enabled 1
		writen /proc/ppm/policy_status 1
		writen /sys/devices/system/cpu/cpufreq/policy0/scaling_governor performance
		writen /sys/devices/system/cpu/cpufreq/policy4/scaling_governor performance
		writen /sys/devices/system/cpu/cpufreq/policy6/scaling_governor performance
		writen /sys/block/mmcblk0/queue/scheduler deadline
		writen /sys/block/mmcblk1/queue/scheduler deadline
		writen /sys/block/sda/queue/scheduler deadline
		writen /sys/block/sdb/queue/scheduler deadline
		writen /sys/block/sdc/queue/scheduler deadline
		writen /proc/ppm/policy/hard_userlimit_max_cpu_freq 6969000
		writen /proc/ppm/policy/hard_userlimit_min_cpu_freq 6969000
		writen /dev/cpuset/foreground/cpus 0-7
		writen /dev/cpuset/background/cpus 0-7
		writen /dev/cpuset/system-background/cpus 0-7
		writen /dev/cpuset/top-app/cpus 0-7
		writen /dev/cpuset/restricted/cpus
		writen /dev/stune/background/schedtune.util.max 1
		writen /dev/stune/background/schedtune.util.min 1
		writen /dev/stune/background/schedtune.boost 1
		writen /dev/stune/background/schedtune.prefer_idle 0
		writen /dev/stune/foreground/schedtune.util.max.effective 1
		writen /dev/stune/foreground/schedtune.util.min.effective 0
		writen /dev/stune/foreground/schedtune.util.max 1024
		writen /dev/stune/foreground/schedtune.util.min 0
		writen /dev/stune/foreground/schedtune.boost 13
		writen /dev/stune/foreground/schedtune.prefer_idle 0
		writen /dev/stune/top-app/schedtune.util.max.effective 1024
		writen /dev/stune/top-app/schedtune.util.min.effective 0
		writen /dev/stune/top-app/schedtune.util.max 1024
		writen /dev/stune/top-app/schedtune.util.min 0
		writen /dev/stune/top-app/schedtune.boost 20
		writen /dev/stune/top-app/schedtune.prefer_idle 0
		writen /dev/stune/schedtune.util.min 1024
		writen /dev/stune/schedtune.util.max 1024
		writen /dev/stune/schedtune.util.max.effective 1024
		writen /dev/stune/schedtune.util.min.effective 0
		writen /dev/stune/schedtune.boost 2
		writen /dev/stune/schedtune.prefer_idle 0
		writen /sys/module/pm_hotplug/parameters/loadl 40
		writen /sys/module/pm_hotplug/parameters/loadh 90
		writen /sys/module/pm_hotplug/parameters/loadl_scroff 50
		writen /sys/module/pm_hotplug/parameters/loadh_scroff 100
		writen /sys/module/pm_hotplug/parameters/rate 100
		writen /sys/module/pm_hotplug/parameters/rate_cpuon 400
		writen /sys/module/pm_hotplug/parameters/rate_scroff 400
		writen /sys/module/pm_hotplug/parameters/freq_cpu1on 500000
		writen /sys/devices/system/cpu/cpu0/cpufreq/smooth_target 1
		writen /sys/devices/system/cpu/cpu0/cpufreq/smooth_offset 1
		writen /sys/devices/system/cpu/cpu0/cpufreq/smooth_step 1
	}

	case $* in
		"-g" | "--green")
			printn -l "--- started"
			set_battery_mode
			printn -l "--- finished"
			return 0
		;;
		"-y" | "--yellow")
			printn -l "--- started"
			set_balanced_mode
			printn -l "--- finished"
			return 0
		;;
		"-r" | "--red")
			printn -l "--- started"
			set_gaming_mode
			printn -l "--- finished"
			return 0
		;;
		"-h" | "--help") __magicn_help ;;
		*)
			printn -e "unknown option $*"
			__magicn_help
		;;
	esac
}

pingn() {
	PR_PREFIX="pingn"
	[[ "$(ping -c1 "8.8.8.8" >/dev/null && echo $?)" != "0" ]] && {
		printn -lf "failed"
		printn -e "nitrond: network: unreachable"
		return 1
	} || {
		printn -n "nitrond: network: ok"
		printn -l "connectivity is stable"
		return 0
	}
}

updaten() {
	cmdavail setprop && {
		if [[ "$(getprop ro.nitron.forcecheckupdate)" == "no" ]]; then
			printn -lf "ro.nitron.forcecheckupdate == $(getprop ro.nitron.forcecheckupdate)"
			printn -e "aborted from system variable"
		fi
	} || {
		if [[ "$NITRON_FORCECHECK_UPDATE" == "false" ]]; then
			printn -lf "NITRON_FORCECHECK_UPDATE == ${NITRON_FORCECHECK_UPDATE}"
			printn -e "aborted from system variable"
		fi
	}

	PR_PREFIX="updaten"

	updatealg()
	{
		printn -i "looking for update..."
		cmdavail curl && {
			curl -o "$NITRON_LOG_DIR/nitrond_src_cache" "https://raw.githubusercontent.com/UsiFX/OpenNitroN/nitrond-staging/nitrond" 2>/dev/null
			curl -o "$NITRON_LOG_DIR/nitronh_src_cache" "https://raw.githubusercontent.com/UsiFX/OpenNitroN/nitrond-staging/nitron_headers.sh" 2>/dev/null
			chmod +x "$NITRON_LOG_DIR/nitrond_src_cache"
		} || printn -e "curl is not available in the system, cannot update."
		PR_PREFIX="updaten"
		printn -w "backing up..."
		cp "$0" "$NITRON_LOG_DIR/nitrond_current" >/dev/null
		cp "$HEADER_SOURCE/nitron_headers.sh" "$NITRON_LOG_DIR/nitronh_current" >/dev/null
		[[ "$PLATFORM" == "Android" ]] && {
			printn -w "modifying downloaded update interepter..."
			sed -i '1c\#!/system/bin/sh' "$NITRON_LOG_DIR/nitrond_src_cache"
		}
		if [[ "$(diff "$NITRON_LOG_DIR/nitrond_src_cache" "$NITRON_LOG_DIR/nitrond_current")" ]]; then
			printn -i "updating..."
			cat "$NITRON_LOG_DIR/nitrond_src_cache" > "$0"
		else
			printn -i "Daemon is up to date, $(apin -dv)"
		fi
		if [[ "$(diff "$NITRON_LOG_DIR/nitronh_src_cache" "$NITRON_LOG_DIR/nitronh_current")" ]]; then
			printn -i "attempting to update headers..."
			cat "$NITRON_LOG_DIR/nitronh_src_cache" > "$HEADER_SOURCE/nitron_headers.sh"
		else
			printn -i "Header is up to date, $(apin -hv)"
		fi
		return 0
	}

	rollbackalg()
	{
		if [[ ! -f "$NITRON_LOG_DIR"/nitrond_current ]]; then
			printn -e "previous daemon update cache is unavailable"
		fi
		if [[ ! -f "$NITRON_LOG_DIR"/nitronh_current ]]; then
			printn -e "previous header update cache is unavailable"
		fi
		if [[ "$(diff "$0" "$NITRON_LOG_DIR/nitrond_current")" ]]; then
			printn -n "downgrading..."
			cat "$NITRON_LOG_DIR/nitrond_current" > "$0"
		else
			printn -i "there is no difference between current daemon update(s) and previous one(s)."
		fi
		if [[ "$(diff "$HEADER_SOURCE/nitron_headers.sh" "$NITRON_LOG_DIR/nitronh_current")" ]]; then
			printn -n "attempting to downgrade headers..."
			cat "$NITRON_LOG_DIR/nitronh_current" > "$HEADER_SOURCE/nitron_headers.sh"
		else
			printn -i "there is no difference between current header update(s) and previous one(s)."
		fi
	}

	init()
	{
		printn -n "checking connectivity..."
		printn -l "pinging 8.8.8.8 ..."
		pingn && PR_PREFIX="updaten"; updatealg
	}

	case $* in
		"-a" | "--apply")
			printn -l "--- triggered"
			init
			printn -l "--- finished"

		;;
		"-d" | "--downgrade")
			printn -l "--- triggered"
			printn -l "attempting to downgrade!"
			rollbackalg
			printn -l "--- finished"
		;;
	esac
}

# Bail out if we aren't running as SU
[[ "$(id -u)" -ne "0" ]] && {
	printn -e "Please run the script as SU"
	exit 1
}

__nitron_help() {
	echo "
Usage: nitrond [OPTION] (e.g. nitrond --update)

Commands:
  deviceinfo			~ shows device resource information
  clean				~ wipe stored nitron data

Options:
  -sdm, --show-default-mode     ~ prints current tweaking mode
  -sg, --set-green              ~ apply Battery mode
  -sr, --set-red                ~ apply Gaming mode
  -sy, --set-yellow             ~ apply Balanced mode
  -c, --console-mode            ~ enter User-Friendly user selections

Others:
  -h, --help                    ~ shows this Help menu
  -v, --version                 ~ shows tool version
  -u, --update                  ~ update to latest

Advanced:
  -dd, --downgrade		~ downgrade to previous upgrade
  -d, --debug                   ~ run commands under debuggable verbose flags
"
}

if [[ $# -eq "0" ]]; then
	tty -s
	__nitron_help
else
	for arg in "$@"
	do
		case "${arg}" in
			"deviceinfo")
				apin -rc
			;;
			"clean")
				apin -c
			;;
			"-sg" | "--set-green")
				magicn -g
				printn -n "nitrond: current mode: $(apin -mc)"
				apin -as
			;;
			"-sr" | "--set-red")
				magicn -r
				printn -n "nitrond: current mode: $(apin -mc)"
				apin -as
			;;
			"-sy" | "--set-yellow")
				magicn -y
				printn -n "nitrond: current mode: $(apin -mc)"
				apin -as
			;;
			"-sdm" | "--show-default-mode")
				printn -i "mode: $(apin -mc)"
			;;
			"-v" | "--version")
				echo -e "Nitron Daemon $(apin -dv) - nitron_headers $(apin -hv)
Copyright (C) 2022-2023 UsiFX <xprjkts@gmail.com>
Copyright (C) 2022-2023 Kartik728 <titanupdates728@gmail.com>

This program may be freely redistributed under
the terms of the GNU Generic Public License."
			;;
			"-c" | "--console-mode")
				if cmdavail dialog; then
					console_dialog
					printn -l "--- started"
				else
					printn -lf "dialog not found, switch: console_legacy()"
					console_legacy
				fi
			;;
			*"?"* | "h"* | "-h" | "--help") __nitron_help ;;
			"-u" | "--update") updaten -a; return 0 ;;
			"-d" | "--debug")
				set -x 2>"$NITRON_LOG_DIR"/nitron.verbose.log
				printn -w "execution under debug, please provide arguments to debug"
				printn -w "verbose is saved at: $NITRON_LOG_DIR/nitron.verbose.log"
			;;
			"-dd" | "--downgrade") updaten -d ;;
			*) printn -e "unknown option $*, check 'nitrond --help'." ;;
		esac
	done
fi
